version: 1
update_configs:
  - package_manager: "javascript"
    target_branch: "master"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "in_range"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: ""
